apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-node
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - name: pod-node
        image: ahmed1399/build-image
        ports:
        - containerPort: 80