apiVersion: v1
kind: Service
metadata:
  name: service-name
spec:
  selector:
    app: nodejs
  ports:
  - port: 8080
    targetPort: 3000
  # Type of Services: ClusterIP, NodePort, LoadBalancer, ExternalName, Ingress
  type: NodePort